In [9]:
!git clone https://github.com:VenkteshV/question_gen_PAWS_ADS.git

Cloning into 'question_gen_PAWS_ADS'...
fatal: unable to access 'https://github.com:VenkteshV/question_gen_PAWS_ADS.git/': Port number ended with 'V'


In [1]:
!pip install scann

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 10.5 MB 5.1 MB/s 
     |████████████████████████████████| 588.3 MB 19 kB/s 
     |████████████████████████████████| 439 kB 64.8 MB/s 
     |████████████████████████████████| 6.0 MB 56.1 MB/s 
     |████████████████████████████████| 1.7 MB 42.0 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.9.0
    Uninstalling tensorflow-estimator-2.9.0:
      Successfully uninstalled tensorflow-estimator-2.9.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.9.1
    Uninstalling tensorboard-2.9.1:
      Successfully uninstalled tensorboard-2.9.1
  Attempting uninstall: keras
    Found existing installation: keras 2.9.0
    Uninstalling keras-2.9.0:
      Successfully uninstalled keras-2.9.0
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 1.

In [ ]:
import scann
import pandas as pd

In [ ]:
df = pd.read_csv('./drive/MyDrive/nq-project/article_data.csv')
df = df.dropna()

In [ ]:
df

topic  \
0              inverted index   
1    simple conjunctive query   
2                  dictionary   
3                intersection   
4                  vocabulary   
..                        ...   
159         language modeling   
160       text classification   
161     document-cluster pair   
162           soft clustering   
163   hierarchical algorithms   

                                               summary  
0    In computer science, an inverted index (also r...  
1    Data integration involves combining data resid...  
2    Wiktionary (UK:  WIK-shə-nər-ee, US:  WIK-shə-...  
3    In mathematics, the intersection of two or mor...  
4    A vocabulary is a set of familiar words within...  
..                                                 ...  
159  A modeling language is any artificial language...  
160  Document classification or document categoriza...  
161  In information retrieval, tf–idf (also TF*IDF,...  
162  Cluster analysis or clustering is the task of ...  
163  In data mining and statistics, hierarchical cl...  

[164 rows x 2 columns]

In [ ]:
!pip install transformers
!pip install tensorboard
!pip install sentence_transformers
import pandas as pd
import numpy as np
import torch
import pandas as pd
from time import time
from transformers import AutoTokenizer, AutoModel, AutoModelForSequenceClassification
import tensorflow_hub as hub # For USE
from sentence_transformers import SentenceTransformer
import os
import tensorflow as tf
import datetime
from tensorboard.plugins import projector


def generate_embeddings(data_ls):
    model = SentenceTransformer('paraphrase-MiniLM-L6-v2')
    embeddings = model.encode(data_ls)
    return embeddings

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.8 MB 30.8 MB/s 
     |████████████████████████████████| 182 kB 45.7 MB/s 
     |████████████████████████████████| 7.6 MB 43.9 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 85 kB 4.8 MB/s 
     |████████████████████████████████| 1.3 MB 47.6 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=f55e91b2c75fbc0fc99e71670f5a9408ce0e52151f99bae59cf8deb9a39152d7
  Stored in directory: /root/.cache/pip/wheels/5e/6f/8c/d88aec621f3f542d26fac0342bef5e693335d125f4e54aeffe
Successfully built sentence-transformers


In [ ]:
count = 0
sentences = []
for i in df['summary']:
  if  type(i) != type("") or len(i) <= 0 :
    count+=1
  else:
    sentences.append(i.replace("\n",' '))

print(count, " sentences removed.")

0  sentences removed.


In [ ]:
len(sentences)

164

In [ ]:
t =time()
embeds = generate_embeddings(sentences)
print("Time taken: " , int((time() - t)%60) ,"s, ", int((time() - t)/60), "m")

Downloading:   0%|          | 0.00/690 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.69k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/314 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

Time taken:  22 s,  0 m


In [ ]:
embeds.shape

(164, 384)

In [ ]:
embeds_df = pd.DataFrame(embeds)

In [ ]:
import json
questions = []
answers = []
with open('./drive/MyDrive/nq-project/NQ-open.dev.jsonl') as f:

  for line in f.readlines():
    questions.append(json.loads(line)['question'])
    answers.append(json.loads(line)['answer'])

In [ ]:
len(questions)

3610

In [ ]:
t =time()
embeds_questions = generate_embeddings(questions)
print("Time taken: " , int((time() - t)%60) ,"s, ", int((time() - t)/60), "m")

Time taken:  31 s,  0 m


In [ ]:
embeds_questions.shape

(3610, 384)

In [ ]:
embeds.shape

(164, 384)

In [ ]:
embeds_df = pd.DataFrame(embeds)## articles dataset
embeds_questions_df = pd.DataFrame(embeds_questions) ## natural questions

In [ ]:
!curl https://storage.cloud.google.com/natural_questions/v1.0-simplified/nq-dev-all.jsonl.gz


In [ ]:
!tar -xvzf nq-dev-all.jsonl.gz

tar (child): nq-dev-all.jsonl.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now


In [ ]:
import numpy as np

k = int(np.sqrt(embeds_questions_df.shape[0]))

In [ ]:

searcher = scann.scann_ops_pybind.builder(embeds_questions_df, 10, "dot_product").tree(num_leaves=k, num_leaves_to_search=int(k/20), training_sample_size=2500).score_brute_force(2).reorder(7).build()


In [ ]:
indices = searcher.search(embeds_df.loc[0])
indices

(array([ 169, 2720,  277, 3236,  550, 3600, 1303, 2416, 2212,  528],
       dtype=uint32),
 array([11.870464 , 11.15177  ,  9.543509 ,  9.137827 ,  8.917534 ,
         7.856188 ,  7.8028293,  7.6533303,  7.580413 ,  7.251926 ],
       dtype=float32))

In [ ]:
pd.DataFrame(questions).loc[indices[0]]

0
169   what type of database is library literature an...
2720    what is the multiplication sign on the computer
277         where is the slide placed on the microscope
3236               where is south pole located on a map
550        what was icq as related to instant messaging
3600  oklahoma's 10 geographic regions are defined b...
1303        what is one element a topographic map shows
2416           what is a dropped pin on google maps for
2212     who invented the cornell method of note taking
528         where is fulda and what is its significance

In [ ]:
questions[169]

'what type of database is library literature and information science'

In [ ]:
pd.DataFrame(sentences).loc[0]

0    In computer science, an inverted index (also r...
Name: 0, dtype: object

In [ ]:
indices = searcher.search(embeds_df.loc[3])
indices

(array([1102, 2475, 3074, 2640, 2404, 1491, 3436, 2790, 2415, 1725],
       dtype=uint32),
 array([10.332722 ,  8.570681 ,  7.495722 ,  7.368865 ,  7.1892395,
         7.0181866,  6.9570823,  6.739656 ,  6.7101316,  6.696864 ],
       dtype=float32))

In [ ]:
pd.DataFrame(questions).loc[indices[0]]

0
1102  distance from one side of a bridge to the othe...
2475   who designed the traffic circle in long beach ca
3074   how many casinos are in atlantic city new jersey
2640          what type of bridge is the charles bridge
2404          philadelphia is known as the city of what
1491  what country shares borders with both belarus ...
3436             where does sex and the city take place
2790          in which city are the wimbledon game held
2415  where do the events in the story take place ge...
1725         the road that connects the tombs is called

In [ ]:
indices = searcher.search(embeds_df[df.topic=='edit distance'].iloc[0])
indices

(array([1114,  893, 2863, 3604, 2212, 3333, 1151, 1320, 3113,  169],
       dtype=uint32),
 array([9.524683 , 7.8025823, 7.1778717, 7.124638 , 6.568034 , 6.512067 ,
        6.3251743, 6.147476 , 6.025811 , 5.8856707], dtype=float32))

In [ ]:
embeds_df[df.topic=='edit distance'].iloc[0]

0     -0.093837
1     -0.139901
2     -0.055061
3     -0.101094
4      0.160006
         ...   
379    0.273782
380    0.057418
381    0.200561
382    0.096391
383    0.054940
Name: 13, Length: 384, dtype: float32

In [ ]:
pd.DataFrame(questions).loc[indices[0]]

0
1114  internet based test of english as a foreign la...
893   a synonym for the content component of communi...
2863     method used by a writer to develop a character
3604  natural resources can be divided into what two...
2212     who invented the cornell method of note taking
3333  who is often associated with printing the firs...
1151                 what does a heart rate of 131 mean
1320  turkish finnish and hungarian belong to which ...
3113  the general term for software that is designed...
169   what type of database is library literature an...

In [ ]:
from bs4 import BeautifulSoup

In [ ]:

nq_sentences = []
with open('/content/drive/MyDrive/nq-project/v1.0-simplified_nq-dev-all.jsonl','r') as f:
  for line in f.readlines():
    soup = BeautifulSoup(json.loads(line)['document_html'], 'html.parser')
    nq_sentences.append(soup.get_text())

In [ ]:
len(nq_sentences)

In [ ]:
t =time()
embeds_nq = generate_embeddings(sentences)
print("Time taken: " , int((time() - t)%60) ,"s, ", int((time() - t)/60), "m")

In [ ]:
embeds_nq_df = pd.DataFrame(embeds_nq)

In [ ]:

searcher = scann.scann_ops_pybind.builder(embeds_nq_df, 10, "dot_product").tree(num_leaves=k, num_leaves_to_search=int(k/20), training_sample_size=2500).score_brute_force(2).reorder(7).build()


In [ ]:
indices = searcher.search(embeds_df[df.topic=='edit distance'].iloc[0])
indices